### ISSUE TITLE
Escape sequences don't behave as needed

### ISSUE THREAD

**Issue by apt1002** [rrthomas/nancy#10]
@tlynn and I identified the following behaviour as surprising or problematic:

```
$ nancy - .
\\
\$
\,
$paste{echo,\}foo}
```

Expected:

```
\
$
,
}foo
```

Observed:

```
\\
\$
\,
\foo}
```

It is not currently possible to include certain strings in certain places in Nancy templates, notably including the source code of C-family languages. For example `$paste{colour_syntax,{ ... }}` is misinterpreted, and there is no way to fix it. I would like to be able to write `$paste{colour_syntax,{ ... \}}`.

**Comment by rrthomas** [comment]
Note: ​Tom Lynn points out that using look-behind to match escape sequences is inherently bug-prone, because no finite look-behind is sufficient to disambiguate the grammar. The relevant example is something like "\\\\\\\\\\$path". You have to parse in left-to-right order to pair off the "\" characters correctly.

**Comment by rrthomas** [comment]
The behaviour is clearly documented, so it's not wrong. I'll have a think about whether I can do something better straightforwardly. In particular, supporting arbitrary "long strings" in the arguments of Nancy commands is not (currently) a goal.

**Comment by rrthomas** [comment]
I think that the use of look-behind only matters in the case that the syntax is extended along the lines you suggest, and not as currently documented; do correct me if that's wrong.

**Comment by rrthomas** [comment]
I think the root problem is one of principle. Nancy tries to have a minimal impact on the syntax of files in which it is used, and hence defines a minimal "external" syntax (recognising the boundaries of a Nancy macro), and a consistent "internal" syntax (the contents of the command).

This is a major part of the motivation behind the FIXME to add redefinable syntax: so that the syntax can be made compatible with languages it doesn't currently support well, and where possible, support perfectly interoperable syntax (this would be possible in XML, using namespaces).

Hence, I'm inclined not to add support for escapes outside macro calls, and lookbehind is not problematic (because it makes no sense to add more than one backslash before a $ command).

However, the main motivation for this issue is to be able to add less-constrained text _inside_ Nancy macro calls, so the argument above does not apply (I think the context is still useful, though).

It would certainly complicate Nancy. It would seem necessary to add some sort of "long delimiter" support to avoid escaping hell, especially when the nested language uses the same escape character (and backslash is a common choice).

So I wonder what the big win for being able to include literal text over putting it in files (which is how Nancy has mainly been used up to now); this has the advantage of keeping syntactic complications (mostly) on the outside of macro calls? I'm not convinced by your example of code snippets that it's a good idea (why not put them in separate files?).

In any case, redefinable syntax would mostly obviate the problem, while also making Nancy properly "syntax-neutral".

**Comment by apt1002** [comment]
Fair enough. As per our IRL conversation, I think I'd misunderstood the direction you wanted to take Nancy in.

A quick reminder: in README.md, it would be helpful to follow this:

> Now I can talk about \$paste.

with its output, as it would make it clear which is which. It's already clear to a careful reader, but not apparently to me!

**Comment by rrthomas** [comment]
Done, thanks.
